name: mlarchive

services:  
  parser:
    build:
      context: ./
      dockerfile: ./parser/container/Dockerfile

    environment:
      INPUT_DIR: "/parser/input"
      OUTPUT_DIR: "/parser/output"
    stdin_open: true
    user: "${UID}:${GID}"
    volumes:
      - ./output:/parser/input:z
      - ./parser_output:/parser/output:z
      - ./parser/src:/parser/src:z
