name: analysis

services:
  analysis:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      INPUT_DIR: "/input"
    stdin_open: true
    user: "${UID}:${GID}"
    volumes:
      - ./src/:/app/src/
      - ./results/:/app/results/:z
      - ../parser_output/parsed/:/input:z
      - ../anonymizer_output:/anonymousinput:z
    ports:
      - 8888:8888 
    command: uv run python src/make_analysis.py
    
    #jupyter notebook --notebook-dir='/app/src' --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
