name: Lint and Test Rust Component

on:
  workflow_dispatch:
  pull_request:
    paths:
    - 'mlh-archiver/**'
  push:
    paths:
    - 'mlh-archiver/**'

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  # Make sure rustc errors on warnings in the CI
  RUSTFLAGS: -Dwarnings

permissions: read-all

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test

  rust-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo fmt --check

  rust-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy --all-features --all-targets

  cargo-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo doc --all-features --no-deps

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Writes changes in the local checkout
        uses: crate-ci/typos@v1
        with:
          write_changes: true
